const SUBSCRIPTION_STATUSES = [
  'TRIAL',
  'ACTIVE',
  'EXPIRED',
  'CANCELLED',
  'SUSPENDED',
];

const BILLING_INTERVALS = ['MONTHLY', 'YEARLY'];

const DEFAULT_TRIAL_DAYS = Number(process.env.DEFAULT_TRIAL_DAYS) || 14;
const DEFAULT_PLAN_NAME = process.env.DEFAULT_PLAN_NAME || 'FREE';

module.exports = {
  SUBSCRIPTION_STATUSES,
  BILLING_INTERVALS,
  DEFAULT_TRIAL_DAYS,
  DEFAULT_PLAN_NAME,
};
